const orderData =[{
    id:1,
    title: "Dosa",
    type:"Vegitarian",
    Cusine: "South Indian",
    price: 50,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "14-30PM",
    amount:1,
    },
{
id:2,
title: "Veg Noodles",
type:"Vegitarian",
Cusine: "South Indian",
price: 168,
ORDER_DATE: "1-7-2022",
ORDER_TIME: "14-30PM",
amount:1,
},{
    id:3,
    title: "FrideRice",
    type:"Vegitarian",
    Cusine: "South Indian",
    price: 168,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "14-35PM",
    amount:1,
    },
{
 id:4,
title: "Veg-biriyani",
type:"Vegitarian",
Cusine: "South Indian",
price: 100,
ORDER_DATE: "1-7-2022",
ORDER_TIME: "4:00PM",
amount:1,
},
{
    id:5,
   title: "Chapathi",
   type:"Vegitarian",
   Cusine: "South Indian",
   price: 50,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "5:00PM",
   amount:1,
   }, 
   {
    id:6,
   title: "Chapathi",
   type:"Vegitarian",
   Cusine: "South Indian",
   price: 50,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "6:00PM",
   amount:1,
   }, 
   {
    id:7,
   title: "Mutton sukka",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 350,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "7:00PM",
   amount:1,
   }, 
   {
    id:8,
   title: "Mutton sukka",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 350,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "7:40PM",
   amount:1,
   }, 
   {
    id:9,
   title: "Chicken manjurian",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 289,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "8:40PM",
   amount:1,
   }, 
   {
    id:10,
   title: "Chicken manjurian",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 289,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "8:45PM",
   amount:1,
   }, 
   {
    id:11,
   title: "Chicken biriyani",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 289,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "8:55PM",
   amount:1,
   }, 
   {
    id:12,
   title: "Chickenbiriyani",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 289,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "9:00PM",
   amount:1,
   }, 
   {
    id:13,
   title: "Dragon chicken",
   type:"non-Veg",
   Cusine: "South Indian",
   price: 280,
   ORDER_DATE: "1-7-2022",
   ORDER_TIME: "8:00PM",
   amount:1,
   }, 
   {
    id:14,
    title: "Hazelnut Brownie",
    type:"desserts" ,
    price: 149,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:35PM",
},
{
    id:15,
    title: "Banana Lava Cake",
    type:"desserts" ,
    price: 169,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:35PM",
},
{
    id:16,
    title: "RedVelvet-Pastry",
    type:"desserts" ,
    price: 169,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:40PM",
},
{
    id:17,
    title: "RedVelvet-Pastry",
    type:"desserts" ,
    price: 169,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:45PM",
},
{
    id:18,
    title: "Indulgence Brownie",
    type:"desserts" ,
    price: 169,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:50PM",
},
{
    id:19,
    title: "Mutton sukka",
    type:"non-Veg" ,
    price: 350,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "8:50PM",
},
{
    id:20,
    title: "Mutton biriyani",
    type:"non-Veg" ,
    price: 150,
    amount:1,
    ORDER_DATE: "1-7-2022",
    ORDER_TIME: "9:00PM",
},

]

    export default orderData;